version: '3.3'
services:
  db:
    env_file:
      - env-mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${PROJECT_NAME}
  backend:
    env_file:
      - env-mysql.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  celeryworker:
    env_file:
      - env-mysql.env
      - env-backend.env
    environment:
      - SERVER_HOST=https://${DOMAIN}
